# [INFO]
site_name: Xinlei's Page
site_url: https://guanqing-github.github.io/personal-wbsite/
site_author: Xinlei
site_description: Xinlei's Personal Website

# [Navigation]
nv:
 - Course Notes:
   - System Dynamics: System Dynamics/Review Outline for System Dynamics.md
   - Data Structure:
     - Introduction: Data Structure/CH1~3 Introduction and Algorithm Analysis.md
     - List, Stack and Queue: Data Structure/CH4 Lists, Stacks, and Queues.md
     - Binary Tree: Data Structure/CH5 Binary Tree.md
     - Overall: Data Structure/CH 7 Internal Sorting.md
   - Classical Control Theory: 
     - Lecture Summary 1: Classical Control Theory/Lecture Summary 1.md
   - Heat Transfer:
     - Week 7: Heat Transfer/Week 7/Week 7.md
   
 - Award & Honor:
   - 2023 MCM: 2023MCM/2023MCM.md

 - Speech Notes:
   - SYS20230316: Speech/[SYS20230316]Notes.md
   - SYS20230406: Speech/[SYS20230406]Notes.md
  
 - CV: Academic Resume/academic_resume.md
 
 - Research Papers:
   - Magnetic Estimation: Research_Papers/On_Ambiguity_in_6-DoF_Magnetic_Pose_Estimation.md
  
# [UI]
## [top]
theme:
  name: material
  palette:
    - scheme: default # 日间模式
      primary: indigo # 上方的
      accent: orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - navigation.expand # 打开Tab时左侧目录全部展开
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - content.code.copy # 可以通过按钮复制代码
    - content.action.edit # 点击按钮跳转到编辑页面  需要结合 edit_uri 一起使用
  language: zh # 一些提示性的文字会变成中文
  
# [Extension]
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
 # - pymdownx.pathconverter:
 #     base_path: 'personal-website' # default: ''
 #     relative_path: '' # default ''
 #     absolute: true # default: false
 #     tags: 'a script img link object embed'

extra_javascript:
  # latex支持
  # check https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math for more information
  # notice `curl https://polyfill.io/v3/polyfill.min.js?features=es6 > docs/mkdocs/javascripts/polyfill.min.js && curl https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js > docs/mkdocs/javascripts/tex-mml-chtml.js` not works... because there are other resources that need to load
  - mkdocs/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # https://cdn.bytedance.com/?query=mathjax&version=3.2.0

