# [INFO]
site_name: Xinlei's Page
  #site_url: https://guanqing-github.github.io/personal-wbsite/
  #site_author: Xinlei
  #site_description: Xinlei's Personal Website
  
# [UI]
## [top]
theme:
  name: material
