# [INFO]
site_name: Xinlei's Page
site_url: https://guanqing-github.github.io/personal-wbsite/
site_author: Xinlei
site_description: Xinlei's Personal Website

# [Navigation]
-nv:
 -Academic Resume: Academic Resume/academic_resume.md
 -2023 MCM: 2023MCM/2023MCM.md
 -Data Structure:
  -Introduction: Data Structure/CH1~3 Introduction and Algorithm Analysis.md
  -Binary Tree: Data Structure/CH5 Binary Tree.md
# [UI]
## [top]
theme:
  name: material
